export { default as Home } from './Home'
export { default as Login } from './Login'
export { default as Census } from './Census'
export { default as Statistics } from './Statistics'
export { default as Results } from './Results'
